// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybZY9U0lvClRv4tfXvBxxFPpWOz3e6dc',
    appId: '1:409889097164:web:a6973965c036f6d56bc969',
    messagingSenderId: '409889097164',
    projectId: 'opendot-0',
    authDomain: 'opendot-0.firebaseapp.com',
    storageBucket: 'opendot-0.appspot.com',
    measurementId: 'G-XN38JJY55S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3aPQIKJwpW3LGmtoFu2GRX8yNy2toXLk',
    appId: '1:409889097164:android:21b992ac858d83826bc969',
    messagingSenderId: '409889097164',
    projectId: 'opendot-0',
    storageBucket: 'opendot-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDD7hpkCoD1Z5aiE-iNqIgTa2eFygLSdg',
    appId: '1:409889097164:ios:10447522fa67bc2a6bc969',
    messagingSenderId: '409889097164',
    projectId: 'opendot-0',
    storageBucket: 'opendot-0.appspot.com',
    iosClientId: '409889097164-s1ncvu3rv8qqa16ce7iiuion22l9nteu.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDD7hpkCoD1Z5aiE-iNqIgTa2eFygLSdg',
    appId: '1:409889097164:ios:30c6b0d6f0f4b6136bc969',
    messagingSenderId: '409889097164',
    projectId: 'opendot-0',
    storageBucket: 'opendot-0.appspot.com',
    iosClientId: '409889097164-n5gjkohj0kh010u6alq5au47o36epoa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp.RunnerTests',
  );
}
